export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE'

export const EDIT_ARTICLE = 'EDIT_ARTICLE'

export const FULL_DATE = 'MMMM DD, YYYY'
